name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # karena kita pakai theme dari submodule

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.2' 
          extended: true
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL.TOKEN }}
          publish_dir: ./public
          publish_branch: main  # karena repo `agusdeo.github.io` pakai branch `main`
          external_repository: agusdeo/agusdeo.github.io
